services:

  dagster_psql:
    image: postgres:11
    container_name: dagster_dev_postgresql
    environment:
      POSTGRES_USER: 'postgres_user'
      POSTGRES_PASSWORD: 'postgres_password'
      POSTGRES_DB: 'postgres_db'
    networks:
      - dagster_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres_user -d postgres_db']
      interval: 10s
      timeout: 8s
      retries: 5

  aquaduct_pipelines:
    environment:
      DAGSTER_POSTGRES_USER: 'postgres_user'
      DAGSTER_POSTGRES_PASSWORD: 'postgres_password'
      DAGSTER_POSTGRES_DB: 'postgres_db'
      DAGSTER_POSTGRES_HOSTNAME: dagster_psql

  dagster_webserver:
    environment:
      DAGSTER_POSTGRES_USER: 'postgres_user'
      DAGSTER_POSTGRES_PASSWORD: 'postgres_password'
      DAGSTER_POSTGRES_DB: 'postgres_db'
      DAGSTER_POSTGRES_HOSTNAME: dagster_psql
    depends_on:
      dagster_psql:
        condition: service_started
      aquaduct_pipelines:
        condition: service_started

  dagster_daemon:
    environment:
      DAGSTER_POSTGRES_USER: 'postgres_user'
      DAGSTER_POSTGRES_PASSWORD: 'postgres_password'
      DAGSTER_POSTGRES_DB: 'postgres_db'
      DAGSTER_POSTGRES_HOSTNAME: dagster_psql
    depends_on:
      dagster_psql:
        condition: service_started
      aquaduct_pipelines:
        condition: service_started
